Translate overview of react on tutorial page
reactjs/bn.reactjs.org pull request #89
Opened 2020-10-25 11:48 UTC by oxfordhalfblood

As Tutorial Page(Overview) is huge, I chunked it into following sections:

- [ ] Overview:
    - [ ] What is React
    - [ ] Inspecting the Starter Code
    - [ ] Passing Data Through Props
    - [ ] Making an Interactive Component
    - [ ] Developer Tools

This PR only covers the What is React & Inspecting the Starter Code.

N.B: This is my first PR in this repo. Let me know if you have any feedback! 

Note to Hacktoberfest 🎃 participants:

While we appreciate the enthusiasm, we are experiencing a high volume of drive-by pull requests (one-line changes, README tweaks, etc.). Please remember that hundreds of people are subscribed to this repo and will receive notifications for these PRs. Spam submissions will be closed and won't count towards your Hacktoberfest goals.

Please search for issues tagged [`good first issue`][gfi] or [`hacktoberfest`][hacktoberfest] to find things to work on.

You can also search [all of GitHub][all].

[gfi]: https://github.com/reactjs/reactjs.org/issues?q=is%3Aissue+is%3Aopen+label%3A"good+first+issue"
[hacktoberfest]: https://github.com/reactjs/reactjs.org/issues?q=is%3Aissue+is%3Aopen+label%3A"good+first+issue"
[all]: https://github.com/search?q=is%3Aissue+hacktoberfest

2020-10-25 12:14 UTC, oxfordhalfblood commented
@nutboltu is there a way to add WIP label? 
And, could we please add #[15](https://github.com/reactjs/bn.reactjs.org/pull/15) under Core Pages, if possible? 
Reckon, it'd would be helpful to quickly find which parts been done.

2020-10-25 12:49 UTC, nutboltu commented
@oxfordhalfblood you can convert the PR as a draft instead of WIP label. See the SS to convert it to draft PR.
![Screen Shot 2020-10-25 at 11 47 56 pm](https://user-images.githubusercontent.com/9896958/97107633-ac2bb200-171c-11eb-933e-1aa51e8650bc.png)

2020-10-26 09:33 UTC, oxfordhalfblood commented on content/tutorial/tutorial.md
> +React হচ্ছে UI তৈরির জন্য বর্ণনামূলক, কার্যকর এবং ফ্লেক্সিবল জাভাস্ক্রিপ্ট লাইব্রেরি। এটি "components" নামক ক্ষুদ্র কোড খন্ড থেকে জটিল UI গঠন করতে সাহায্য করে।
should we:
flexible- পরিবর্তনযোগ্য ?

2020-10-26 13:48 UTC, Twaha-Rahman commented on content/tutorial/tutorial.md
> +React হচ্ছে UI তৈরির জন্য বর্ণনামূলক, কার্যকর এবং ফ্লেক্সিবল জাভাস্ক্রিপ্ট লাইব্রেরি। এটি "components" নামক ক্ষুদ্র কোড খন্ড থেকে জটিল UI গঠন করতে সাহায্য করে।
How about `নমনীয়`?

2020-10-26 14:34 UTC, Twaha-Rahman commented on content/tutorial/tutorial.md
> +React হচ্ছে UI তৈরির জন্য বর্ণনামূলক, কার্যকর এবং ফ্লেক্সিবল জাভাস্ক্রিপ্ট লাইব্রেরি। এটি "components" নামক ক্ষুদ্র কোড খন্ড থেকে জটিল UI গঠন করতে সাহায্য করে।
Or how about `অভিযোজনশীল`?

2020-10-28 01:35 UTC, oxfordhalfblood commented on content/tutorial/tutorial.md
> +React হচ্ছে UI তৈরির জন্য বর্ণনামূলক, কার্যকর এবং ফ্লেক্সিবল জাভাস্ক্রিপ্ট লাইব্রেরি। এটি "components" নামক ক্ষুদ্র কোড খন্ড থেকে জটিল UI গঠন করতে সাহায্য করে।
haha in that case, I’d sit with a B2E dictionary to read this tutorial 😄 just my opinion though.

As `flexible` is more popular than its translations, maybe we could leave it as it is?
I saw we’re okay to use english when appropriate:
https://github.com/reactjs/bn.reactjs.org/pull/8/files#diff-190bcdff0a94302f2710b94ff16508211613b9b700f4a1b77e20953afa7b4a72R50

2020-10-31 10:46 UTC, Twaha-Rahman commented on content/tutorial/tutorial.md
> +React হচ্ছে UI তৈরির জন্য বর্ণনামূলক, কার্যকর এবং ফ্লেক্সিবল জাভাস্ক্রিপ্ট লাইব্রেরি। এটি "components" নামক ক্ষুদ্র কোড খন্ড থেকে জটিল UI গঠন করতে সাহায্য করে।
Sure. If we agree to keep it untranslated, at least we should type it in Bangla. We might also want to add it to the [grocery](https://github.com/reactjs/bn.reactjs.org/wiki/Glossary).

@nutboltu Any thoughts?

2020-10-31 12:41 UTC, nutboltu commented on content/tutorial/tutorial.md
> +React হচ্ছে UI তৈরির জন্য বর্ণনামূলক, কার্যকর এবং ফ্লেক্সিবল জাভাস্ক্রিপ্ট লাইব্রেরি। এটি "components" নামক ক্ষুদ্র কোড খন্ড থেকে জটিল UI গঠন করতে সাহায্য করে।
@Twaha-Rahman @oxfordhalfblood
We usually follow this [Glossary](https://github.com/reactjs/bn.reactjs.org/wiki/Glossary). Though it's not fully complete, feel free to take it as a reference.

Regarding the word, `flexible`, I think we can still translate it into `সহজে পরিবর্তনীয়` or `পরিবর্তনযোগ্য` keeping the reader's convenience in mind.

@oxfordhalfblood if your PR is ready for review, please update it from draft to ready. It'll help us to start reviewing 👍

2020-11-02 12:13 UTC, nutboltu commented on content/tutorial/tutorial.md
> +শীঘ্রই আমরা XML-এরমতো মজার ট্যাগগুলো দেখতে যাচ্ছি। কম্পোনেন্ট ব্যাবহার করে আমরা React কে বলি আমরা স্ক্রিনে কি দেখতে চাই। যখন আমাদের ডাটা পরিবর্তিত হয়, React সুদক্ষভাবে কম্পোনেন্টগুলো আপডেট করে এবং পু
ব্যাবহার -> ব্যবহার

2020-11-02 12:13 UTC, nutboltu commented on content/tutorial/tutorial.md
> +এখানে ShoppingList হল একটি **React component class** অথবা **React component type**। একটি কম্পোনেন্ট একাধিক প্যারামিটার ("properties" এর সংক্ষেপ) নেয় যেগুলোকে `props` বলে, এবং `render` মেথডের সাহায্যে
```suggestion
এখানে ShoppingList হল একটি **React component class** অথবা **React component type**। একটি কম্পোনেন্ট একাধিক প্যারামিটার নেয় যেগুলোকে `props` ("properties" এর সংক্ষেপ) বলে, এবং `render` মেথডের সাহায্যে প্রদর্শনযোগ্য ভিউগুলোর ক্রমোচ্চ শ্রেণীবিন্যাস রিটার্ন করে।
```

2020-11-02 12:21 UTC, oxfordhalfblood commented on content/tutorial/tutorial.md
> +React হচ্ছে UI তৈরির জন্য বর্ণনামূলক, কার্যকর এবং ফ্লেক্সিবল জাভাস্ক্রিপ্ট লাইব্রেরি। এটি "কম্পোনেন্ট" নামক ক্ষুদ্র কোড খন্ড থেকে জটিল UI গঠন করতে সাহায্য করে।
Just wondering why do we prefer ছোট অংশের instead of ক্ষুদ্র কোড খন্ড ?

2020-11-02 12:23 UTC, nutboltu requested changes
We have a separate task to translate the entire `content/tutorial/nav.yml` file. Let's revert it back to its previous state.

2020-11-02 12:23 UTC, nutboltu commented on content/tutorial/tutorial.md
> +আমরা স্ক্রিনে যা দেখতে চাই `render` মেথডটি তার একটি *বর্ণনা* রিটার্ন করে। React বর্ণনাটি গ্রহণ করে তার ফলাফল প্রদর্শন করে। বিশেষভাবে, `render` একটি **React element**, অর্থাৎ যা দেখাতে হবে তার একটি হা
যেমন উপড়ের উদাহরণের সমতুল্য হলঃ -> যেমন উপরের উদাহরণের মতন হলঃ

2020-11-02 12:23 UTC, nutboltu commented on content/tutorial/tutorial.md
> +আগ্রহী থাকলে [API রেফারেন্সে](/docs/react-api.html#createelement) `createElement()` এর সবিস্তারে বর্ণনা পাবেন, কিন্তু আমরা এই টিউটোরিয়ালে তা প্রয়োগ করছিনা। এর পরিবর্তে আমরা JSX ব্যাবহার করব।
ব্যাবহার -> ব্যবহার

2020-11-02 12:23 UTC, nutboltu commented on content/tutorial/tutorial.md
> +উপড়ের `ShoppingList` কম্পোনেন্টটি শুধুমাত্র বিল্ট-ইন DOM কম্পোনেন্ট যেমন `<div />` এবং `<li />` রেন্ডার করে। কিন্তু আপনি কাস্টম React কম্পোনেন্টও কম্পোজ এবং রেন্ডার করতে পারবেন। যেমন, এখন আমরা `<Shop
উপড়ের -> উপরের

2020-11-02 12:23 UTC, nutboltu commented on content/tutorial/tutorial.md
> +কোড নিরীক্ষণ করে, আপনি লক্ষ করবেন যে এখানে তিনটি React কম্পোনেন্ট আছেঃ
লক্ষ -> লক্ষ্য

2020-11-02 12:23 UTC, nutboltu commented on content/tutorial/tutorial.md
> +Square কম্পোনেন্টটি একটিমাত্র `<button>` রেনডার করে এবং Board রেনডার করে ৯টি স্কোয়ার। Game কম্পোনেন্টটি প্লেসহোলডার ভ্যালুসহ একটি বোর্ড রেনডার করে যেটা আমরা পরে পরিবর্তন করব। বর্তমানে এখানে কোনো ইন্ট
রেনডার -> রেন্ডার

As `placeholder` is a renowned  Web API attribute, let's keep it unchanged.

2020-11-02 12:43 UTC, oxfordhalfblood commented on content/tutorial/tutorial.md
> +Square কম্পোনেন্টটি একটিমাত্র `<button>` রেনডার করে এবং Board রেনডার করে ৯টি স্কোয়ার। Game কম্পোনেন্টটি প্লেসহোলডার ভ্যালুসহ একটি বোর্ড রেনডার করে যেটা আমরা পরে পরিবর্তন করব। বর্তমানে এখানে কোনো ইন্ট
Thanks, makes sense- that we could add in the [Glossary](https://github.com/reactjs/bn.reactjs.org/wiki/Glossary) for later reference.

2020-11-02 12:45 UTC, oxfordhalfblood commented on content/tutorial/tutorial.md
> +React হচ্ছে UI তৈরির জন্য বর্ণনামূলক, কার্যকর এবং ফ্লেক্সিবল জাভাস্ক্রিপ্ট লাইব্রেরি। এটি "components" নামক ক্ষুদ্র কোড খন্ড থেকে জটিল UI গঠন করতে সাহায্য করে।
b84b3fa71a8f2dba4c191ec3567ae8fcdb0178fc

2020-11-02 13:13 UTC, nutboltu commented on content/tutorial/tutorial.md
> +React হচ্ছে UI তৈরির জন্য বর্ণনামূলক, কার্যকর এবং ফ্লেক্সিবল জাভাস্ক্রিপ্ট লাইব্রেরি। এটি "কম্পোনেন্ট" নামক ক্ষুদ্র কোড খন্ড থেকে জটিল UI গঠন করতে সাহায্য করে।
it sounds more readable. But surely not a blocker for this PR.

2020-11-02 13:15 UTC, nutboltu approved these changes
@oxfordhalfblood great work! LGTM.

2020-11-02 13:26 UTC, oxfordhalfblood commented
Thank you both for your review 😃

2020-11-02 16:07 UTC, Twaha-Rahman commented
> Thank you both for your review 😃
> What's the process going forward? leaving the PR open and someone else merges it? 

Either @nutboltu or @shakib609 's gonna merge it since they are the one's with write access.

Anyway congrats on your first PR to the repo!

2020-11-02 21:34 UTC, nutboltu commented
@oxfordhalfblood you did a last minute rebase with force push which brings back older changes. Could you please revert it back? then I'll merge this PR.

2020-11-02 23:50 UTC, nutboltu commented
> Thank you both for your review 😃
> What's the process going forward? leaving the PR open and someone else merges it? @nutboltu

@oxfordhalfblood you did a last minute rebase with force push which brings back older changes. Could you please revert it back? then I'll merge this PR.

2020-11-04 01:08 UTC, oxfordhalfblood commented
Ahh apologies reverted it @nutboltu Although it's showing vercel needs auth, not sure .

2020-11-04 01:21 UTC, nutboltu approved these changes

2020-11-04 01:22 UTC, nutboltu commented
@oxfordhalfblood no worries. As we don't need a branch deployment for this changes, we can omit this check. going to merge this PR.

Great work!

2020-11-04 01:22 UTC, merged